FROM nvidia/cuda:8.0-devel-ubuntu16.04
RUN mkdir /drake
COPY . /drake
RUN apt-get update && yes "Y" \
      | /drake/setup/ubuntu/16.04/install_prereqs.sh \
      && rm -rf /var/lib/apt/lists/* \
      && apt-get clean all
RUN export PYTHONPATH=${PWD}/install/lib/python2.7/site-packages:${PYTHONPATH}
ENTRYPOINT ["/drake/setup/docker/entrypoint.sh"]
